# Reference: https://build-cpp.github.io/cmkr/cmake-toml
[project]
name = "reframework-exports"

[target.reframework]
type = "interface"
include-directories = ["deps/reframework/include"]

[target.reframework-not-a-plugin]
type = "shared"
sources = ["example/**.cpp"]
headers = ["example/**.hpp"]
compile-features = ["cxx_std_20"]
link-libraries = ["reframework"]

[target.reframework-exports]
type = "shared"
sources = ["src/**.cpp"]
headers = ["src/**.hpp"]
compile-features = ["cxx_std_20"]
link-libraries = ["reframework"]

[[install]]
targets = ["reframework-exports", "reframework-not-a-plugin"]
destination = "bin"