name: CMake
on:
  push:
    branches: [main]
env:
  BUILD_TYPE: Release
jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        project: [reframework-disablesetcursorpos, reframework-exports]
    steps:
    - uses: actions/checkout@v2
    - name: Configure CMake
      run: cmake -S ${{github.workspace}}/${{matrix.project}} -B ${{github.workspace}}/${{matrix.project}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
    - name: Build
      run: cmake --build ${{github.workspace}}/${{matrix.project}}/build --config ${{env.BUILD_TYPE}}
    - name: Install
      run: cmake --install ${{github.workspace}}/${{matrix.project}}/build --prefix ${{github.workspace}}/${{matrix.project}}/install
    - name: Upload artifacts
      uses: actions/upload-artifact@v2.3.1
      with:
        name: ${{matrix.project}}
        path: ${{github.workspace}}/${{matrix.project}}/install/bin/*
        if-no-files-found: error
    - name: Compress artifacts
      uses: vimtor/action-zip@v1
      with:
        files: ${{matrix.project}}/install/bin/
        dest: ${{matrix.project}}.zip
    - name: Release
      uses: softprops/action-gh-release@v0.1.14
      if: ${{startsWith(github.ref, 'refs/tags/')}}
      with:
        prerelease: ${{!startsWith(github.ref, 'refs/tags/v') || contains(github.ref, '-pre')}}
        files: ${{github.workspace}}/${{matrix.project}}.zip
