name: CMake
on:
  push:
    branches: [main]
env:
  BUILD_TYPE: Release
jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        project: [reframework-disablesetcursorpos, reframework-exports]
    steps:
    - uses: actions/checkout@v2
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/${{matrix.project}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
    - name: Build
      run: cmake --build ${{github.workspace}}/${{matrix.project}}/build --config ${{env.BUILD_TYPE}}
    - name: Install
      run: cmake --install ${{github.workspace}}/${{matrix.project}}/build --prefix ${{github.workspace}}/${{matrix.project}}/install
    - name: Upload artifacts
      uses: actions/upload-artifact@v2.3.1
      with:
        name: ${{matrix.project}}
        path: ${{github.workspace}}/${{matrix.project}}/install/bin/*
        if-no-files-found: error
